name: Publish

on:
  release:
    types: [published]

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/tests.yml

  publish:
    name: Publish to crates.io
    needs: test 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_API_TOKEN }}
        run: cargo publish --token $CARGO_REGISTRY_TOKEN